# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20160625_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('idprogress', models.AutoField(db_column='idProgress', primary_key=True, serialize=False)),
                ('progress_text', models.CharField(db_column='ProgressName', max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='progress1_date',
            field=models.DateField(db_column='Progress1_date', null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='progress2_date',
            field=models.DateField(db_column='Progress2_date', null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='progress3_date',
            field=models.DateField(db_column='Progress3_date', null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='progress4_date',
            field=models.DateField(db_column='Progress4_date', null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='progress5_date',
            field=models.DateField(db_column='Progress5_date', null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='progress6_date',
            field=models.DateField(db_column='Progress6_date', null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='progress7_date',
            field=models.DateField(db_column='Progress7_date', null=True),
        ),
    ]
