# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20160705_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarked',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
    ]
